#+LATEX_CLASS_OPTIONS: [11pt]
#+LATEX_HEADER: \usepackage{placeins}
#+OPTIONS: H:4 toc:nil title:nil author:nil date:nil
#+LATEX_HEADER: \input article_setup.tex
#+LATEX_HEADER: \usepackage{url}
#+LATEX_HEADER: \geometry{letterpaper,textwidth=6.4in,textheight=9in,includeheadfoot}

#+BEGIN_EXPORT latex
\author{\normalsize L. Larrabee Strow}
\date{\normalsize \today}
\title{\large\textbf{\textsf{README for Git Repo: cris-nucal}}}
\maketitle
#+END_EXPORT


These codes how how to determine the CrIS in-orbit frequency calibration (ppm offsets from the ENGR PKT values used to generate the radiance data.

-  =test.m= :: Sample run.
-  =sc_opts.m= :: Sets various options and file locations
-  =speccal_rtp.m= :: Main routine to find ppm offsets
-  =test_out= :: Contains output from running test.m
-  =output_j2_v2a_2023_day045.mat= :: Output from running test.m BUT for a whole day's worth of files (240 granules)

The input files for =test.m= are are large on github, so take a while to download.  They can be also be downloaded at \url{https://asl.umbc.edu/pub/packages/cris-nucal/Data/}.  

** Details

These codes input rtp files (hdf4 files that contain both the observed radiances and simnulated radiances derived from ECMWF forcast fields closest to the observations.  Detection of clear scenes is only nominal.   The main use of =speccal_rtp= is for quick analysis of *all* data when trying to derive new focal plane information quickly.  

A second code =speccal_stats.m= inputs very clear scenes derived on a daily basis over ocean.  These input files are aggregated by latitude in 40 bins that are roughly equal area bins.

The "rtp" specification can be found at \url{https://asl.umbc.edu/helppages/packages/rtpspec201/}.
